version: '3'

services:

  api-gateway:
    container_name: api-gateway
    build:
      context: ./../api-gateway
      dockerfile: ./../api-gateway/Dockerfile
    ports:
      - "3000:3000"

  auth-svc:
    container_name: auth-svc
    build:
      context: ./../auth-svc
      dockerfile: ./../auth-svc/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - api-gateway

  order-svc:
    container_name: order-svc
    build:
      context: ./../order-svc
      dockerfile: ./../order-svc/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - auth-svc

  book-svc:
    container_name: book-svc
    build:
      context: ./../book-svc
      dockerfile: ./../book-svc/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - order-svc